apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gabrielcardoso
  name: project2-pv-gabrielcardoso
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi