---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gabrielcardoso
  name: project2-pv-gabrielcardoso
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: project2-pv-gabrielcardoso
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabrielcardoso-playlist-recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gabrielcardoso-playlist-recommender
  template:
    metadata:
      labels:
        app: gabrielcardoso-playlist-recommender
    spec:
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: project2-pv-gabrielcardoso
      containers:
      - name: playlist-recommender
        image: docker.io/gabrielpains/gabrielcardoso-playlists-recommender:7dc06e2
        imagePullPolicy: Always
        volumeMounts:
            - name: pvc-volume
              mountPath: app/shared
        ports:
        - containerPort: 32183
        env:
        - name: API_TAG
          value: "7dc06e2"
        - name: ML_TAG
          value: "0b2e87d"
      - name: playlist-model
        image: docker.io/gabrielpains/gabrielcardoso-playlists-model:0b2e87d
        imagePullPolicy: Always
        volumeMounts:
            - name: pvc-volume
              mountPath: app/shared
        env:
        - name: DATASET_URL
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"