FROM python:3.9-slim-bullseye

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

#WORKDIR /code

#COPY ./requirements.txt /code/requirements.txt


#RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


#COPY ./app /code/app

#CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
